version: "3.8"

services:
  db:
    image: mysql:8.0         
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: fishmon
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      # Jangan set PMA_USER dan PMA_PASSWORD di sini
    ports:
      - '8082:80'

volumes:
  my-db:
